/* Database schema to keep the structure of entire database. */
CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1),
    name varchar(20),
    date_of_birth Date,
    escape_attempts INT,
    neutered Bit,
    weight_kg Decimal,
     PRIMARY KEY (id)
);